[deps]
BenchmarkProfiles = "ecbce9bc-3e5e-569d-9e29-55181f61f8d0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MOProblems = "a5b80fa4-7d73-4f2e-b7b1-8d4a9c5c7c4d"
MOSolvers = "b8c76f4e-5d2a-4c7b-8f8a-3a2d9e6c0e16"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
